#pragma once

/* LEDS */
#define LEDS_RCC RCC_GPIOC
#define LEDS_PORT GPIOC
#define LED_L_GPIO GPIO6
#define LED_R_GPIO GPIO7

/* DEBUG USART */
#define DBG_USART_RCC RCC_USART3
#define DBG_USART USART3
#define DBG_USART_PORT GPIOB
#define DBG_USART_PORT_RCC RCC_GPIOB
#define DBG_USART_TX_GPIO GPIO10
#define DBG_USART_RX_GPIO GPIO11

/* PIC USART */
#define PIC_USART_RCC RCC_USART1
#define PIC_USART USART1
#define PIC_USART_PORT GPIOB
#define PIC_USART_PORT_RCC RCC_GPIOB
#define PIC_USART_TX_GPIO GPIO6
#define PIC_USART_RX_GPIO GPIO7

/* PIC Iface */
#define PIC_RCC RCC_GPIOB
#define PIC_PORT GPIOB
#define PIC_RESET GPIO9
#define PIC_BOOT GPIO8
#define PIC_ICSP_CLK GPIO5
#define PIC_ICSP_DATA GPIO4

/* Brook iface */
#define BROOK_RCC RCC_GPIOC
#define BROOK_PORT GPIOC
#define BROOK_CMD GPIO2

/* VIO */
#define VIO_PORT GPIOC
#define VIO_PIN GPIO0
#define ADC_VIO_CHANNEL 10
